
spring:
  application:
    name: eurekaserver

  security:
    basic:
      enabled: true
    user:
      name: alegodinho
      password: 123456

server:
  port: 8761

  
eureka:  
  client:
    register-with-eureka: false
    fetch-registry: false
    