
spring:
  application:
    name: avaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: godinis22
    password: 123

server:
  port: 0

mq:
  queues:
    emissao-cartoes: EmissaoCartoes

eureka:
  client:
    service-url:
      defaultZone: http://alegodinho:123456@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log