spring:
  application:
    name: cloudgateway

cloud:
  gateway:
    locator:
      enable: true
      lower-case-service-id: true
 
server:
  port: 8080
  
eureka:
  client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
      defaultZone: http://alegodinho:123456@${EUREKA_SERVER}:8761/eureka
  