spring:
  application:
    name: clientes
    
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://alegodinho:123456@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${random.value}}
